### ISSUE TITLE
finding name

### ISSUE THREAD

**Issue by kotzendekrabbe** [kotzendekrabbe/meetsy#5]
meetup-tool as name is to general.
events for calendar, sync events into calendar, help organize events, better overview of events

**from markus**
- Meeter,
- MeetSync
- MeetCLI
- SyncUp

**from feli**
- meetupSynCal
- eventSynCal
- eventSycal
- evsyca (EVentSYncCAlender)
- esyca
- calEventUp
- calSyncMeetup

**from martin**
- MeetupCalSync

**Comment by marionebl** [comment]
Two ideas:

* meetineer
* meetsy

**Comment by kotzendekrabbe** [comment]
@marionebl meetsy 😍

**Comment by kotzendekrabbe** [comment]
sounds like a cat ... haha, i love it!

**Comment by MartinHelmut** [comment]
Isn't this issue closed?

**Comment by kotzendekrabbe** [comment]
jupp, you're right. thanks
