### ISSUE TITLE
Add cli option for secret for global use

### ISSUE THREAD

**Issue by MartinHelmut** [kotzendekrabbe/meetsy#9]
The file `googleApi_clientSecret.json` that needs to be added into the project folder. If it would be possible to add it as a cli option, e.g.: `--secret ./googleApi_clientSecret.json` you could install the package by npm (`npm install meetsy -g`) and use it from everywhere.

**Comment by kotzendekrabbe** [comment]
#10

**Comment by MartinHelmut** [comment]
This issue can be closed.
